version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blue-green-sam"
s3_prefix = "blue-green-sam"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
